---
apiVersion: v1
kind: Service
metadata:
  name: vxlan-ipam
  namespace: system
  labels:
    control-plane: vxlan-ipam
    app.kubernetes.io/name: deployment
    app.kubernetes.io/instance: vxlan-ipam
    app.kubernetes.io/component: vxlan-ipam
    app.kubernetes.io/created-by: neonvm
    app.kubernetes.io/part-of: neonvm
    app.kubernetes.io/managed-by: kustomize
spec:
  clusterIP: None
  ports:
    - port: 9090
      protocol: TCP
      targetPort: grpc
  selector:
    app.kubernetes.io/component: vxlan-ipam
