apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: overlay-net
  namespace: system
spec:
  config: '{
    "cniVersion": "0.3.1",
    "name": "neonvm-overlay-net",
    "type": "bridge",
    "bridge": "neon-br0",
    "ipam": {}
    }'
