FROM debian:bookworm AS build

ARG KERNEL_VERSION

RUN set -e \
    && echo "Build linux  kernel ${KERNEL_VERSION}" \
    && test -n "${KERNEL_VERSION}"

WORKDIR /build

RUN apt-get update && apt-get -y install --no-install-recommends \
    curl \
    ca-certificates \
    fakeroot \
    build-essential \
    ncurses-dev \
    flex \
    bison \
    libelf-dev \
    bc \
    libssl-dev \
    cpio \
    zstd

RUN set -e \
    && mkdir linux \
    && curl -sfL https://cdn.kernel.org/pub/linux/kernel/v6.x/linux-${KERNEL_VERSION}.tar.xz -o linux-${KERNEL_VERSION}.tar.xz \
    && tar --strip-components=1 -C linux -xf linux-${KERNEL_VERSION}.tar.xz

ARG TARGETARCH
ADD hack/linux-config-${KERNEL_VERSION}.${TARGETARCH} linux/.config
RUN cd linux && make -j `nproc` && cp `make image_name` /build/vmlinuz.${TARGETARCH}

FROM scratch
ARG TARGETARCH
COPY --from=build /build/vmlinuz.${TARGETARCH} /vmlinuz.${TARGETARCH}
