apiVersion: vm.neon.tech/v1
kind: VirtualMachine
metadata:
  name: example
spec:
  guest:
    cpus:
      min: 1
      max: 4
      use: 1
    memorySlotSize: 1Gi
    memorySlots:
      min: 1
      max: 16
      use: 1
    rootDisk:
      image: vm-postgres:14-alpine
      size: 8Gi
    ports:
      - port: 5432
