apiVersion: vm.neon.tech/v1
kind: VirtualMachine
metadata:
  name: example
spec:
  guest:
    cpus:
      min: 1
      max: 4
      use: 1
    memorySlotSize: 1Gi
    memorySlots:
      min: 1
      max: 4
      use: 1
    rootDisk:
      image: vm-postgres:14-alpine
      size: 8Gi
    command: ["/bin/sh"]
    args:
      - -c
      - |
        echo "Hello First World"
        echo Hello Second World
        echo $VAR1
        echo $VAR2
        ping 8.8.8.8
    env:
      # for testing only - allows login without password
      - name: VAR1
        value: value1
      - name: VAR2
        value: "value 2"
    ports:
      - port: 5432
