---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vxlan-ipam
  namespace: system
  labels:
    control-plane: vxlan-ipam
    app.kubernetes.io/name: deployment
    app.kubernetes.io/instance: vxlan-ipam
    app.kubernetes.io/component: vxlan-ipam
    app.kubernetes.io/created-by: neonvm
    app.kubernetes.io/part-of: neonvm
    app.kubernetes.io/managed-by: kustomize
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/component: vxlan-ipam
  replicas: 1
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: vxlan-ipam
      labels:
        app.kubernetes.io/component: vxlan-ipam
    spec:
      serviceAccount: vxlan-ipam
      serviceAccountName: vxlan-ipam
      terminationGracePeriodSeconds: 10
      securityContext: {}
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: kubernetes.io/arch
                  operator: In
                  values:
                    - amd64
                - key: kubernetes.io/os
                  operator: In
                  values:
                    - linux
      containers:
      - name: vxlan-ipam
        image: vxlan-controller:dev
        imagePullPolicy: IfNotPresent
        args: ["vxlan-ipam"]
        envFrom:
        - configMapRef:
            name: vxlan-ipam
        ports:
        - containerPort: 9090
          name: grpc
          protocol: TCP
        readinessProbe:
          exec:
            command: ["/usr/bin/grpc_health_probe", "-addr=:9090"]
          initialDelaySeconds: 5
        livenessProbe:
          exec:
            command: ["/usr/bin/grpc_health_probe", "-addr=:9090"]
          initialDelaySeconds: 10
        resources:
          limits:
            cpu: 100m
            memory: 50Mi
          requests:
            cpu: 100m
            memory: 50Mi
