apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
- literals:
  - GOIPAM_CIDR=10.100.0.0/20
  - GOIPAM_LOG_LEVEL=debug
  - GOIPAM_CONFIGMAP_NAME=neonvm-vxlan-ipam-data
  name: vxlan-ipam
  namespace: neonvm-system

generatorOptions:
  disableNameSuffixHash: true

resources:
- deployment.yaml
- service.yaml
- rbac.yaml

images:
- name: vxlan-controller
  newName: vxlan-controller
  newTag: dev
