---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vxlan-ipam
  namespace: system

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: vxlan-ipam
  namespace: system
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "create", "update", "delete"]
    #resourceNames: ["vxlan-ipam"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: vxlan-ipam
  namespace: system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: vxlan-ipam
subjects:
- kind: ServiceAccount
  name: vxlan-ipam
  namespace: system
