name: vm-kernel

on:
  schedule:
    - cron:  '42 4 * * 2'  # run once a week
  workflow_dispatch: # adds ability to run this manually

env:
  VM_KERNEL_IMAGE:   "neondatabase/vm-kernel"
  VM_KERNEL_VERSION: "6.1.14"

jobs:
  vm-kernel:
    runs-on: ubuntu-latest
    steps:

      - name: git checkout
        uses: actions/checkout@v3

      - name: docker - install qemu
        uses: docker/setup-qemu-action@v2
      - name: docker - setup buildx
        uses: docker/setup-buildx-action@v2
      - name: login to docker hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.NEON_DOCKERHUB_USERNAME }}
          password: ${{ secrets.NEON_DOCKERHUB_PASSWORD }}

      - name: build linux kernel for arm64
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          pull: true
          no-cache: true
          file: hack/Dockerfile.kernel-cross .
          tags: ${{ env.VM_KERNEL_IMAGE }}:${{ env.VM_KERNEL_VERSION }}-arm64
          build-args: |
            KERNEL_VERSION=${{ env.VM_KERNEL_VERSION }}
            ARCH=arm64

      - name: build linux kernel for amd64
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          pull: true
          no-cache: true
          file: hack/Dockerfile.kernel-cross .
          tags: ${{ env.VM_KERNEL_IMAGE }}:${{ env.VM_KERNEL_VERSION }}-amd64
          build-args: |
            KERNEL_VERSION=${{ env.VM_KERNEL_VERSION }}
            ARCH=amd64
